dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: bw4mELnCOaMyf8s/mdDHl3H+Y14hRY59iTy9WAZvh1fDVIr/ZUn3IPHAnS59JQ53czyQEPABKqBqnPjJoT/Qa+NhgJlIyKdCZQhgHW147SozMnW/StCw4r44iBEALbF72jwmqGk1aTS4efBUKq1CTYohooNJ4T9lk9xOQvPIwDW6q15AWxsrV2Rq81q21JFpl1WoNsL+kA9t6reWbE46P7PKJdagUvu4FXEajzU3dF9TE/xRejO5IDNycaSgNe+DmPdj4lcx0Wnc2gYH5Wzg2getRqnCez2iZLoydUwLcWdeEO4jqcqtKmXVpOz+1UCIlF7y+0ICY1rIahvR83kPShTQebzbI7a98fhmnWZlyIq27I8HA4cnXZkL1r+I1ROY4ndwXfb5k3LvSwP76Cf6UPgkpMjeJC9b1TrFRivxg8sPq3RssF6F+QOrLZ6fqlCUvY0BHxQUepmfT2pVITdNedaN0SaYNP+TydEDqv3nqGV/JzP0KlihbbeCSXm7er/QnAYydsV5m1w8hK+Qu+1/jjxSHZ2YUsY4/WEUJRwj/3IY3g2pXToyPtPJl1a0DQ6b0YtBLTYQV8W631tQn0rZx5g2GPKQ3Xr/YPz+OYDLSzE8CqNEsfMPzJUnF535QUOdi1hvfPalZG3QQp70PnRAwQK6pWEgr7EXm7nnAc586zQ=
