dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh | bash
notifications:
  slack:
    rooms:
      secure: "THYrW6TZle27GgET0RdVspkqPu60PTKDEhVG0ADwbLvM/p+WkJZ2QhvQEkJKgrE+6di5TvmWQSYnDrkBEBU+b9ahvEIyHoOFd4QOF7Ts94W9Fgf6fZ0OjXvJCCrc2ZxAWfIxnWet5+a36U40BMdrQ2ji7VrPffA5rS0h54Aq4EpXspxx3y5JLDNswdq0z2xIsfUu5k7QtFotQ9Wq3DbGSYTtpn3aJD+u/efaVR4DTOfe8UOM4G6KN1kLAGKVpSC4hGhleX6fbDlqfhAJPhoXXV/ES7+oJAnqoZEVaLyCnUmGM0B8DKDnHnHluvbBEvUZAw337Jz0oXnOYk8P2DeyQfrizFDuIj0WAGLCWT6HzmtTaFW+kXmSrpgJ6Hn162S0hRWpOjaBmsp1og9PrdgQ371I73kX3zPJdDG5agCfS1EL1SOiZnM9JN4WZA3+dT6J4XG+30Cc0MdQFXr4QZ49npWEBTypnl+N1j82Zlo3wfGCmoDzT3GvJpBl407ls2krm+E3OcfY/LaALXX1AnOzW+uk2C2E1qd4QhIqGO4SCBpYU218E1Aqq9uPdkBRuobun+b0Bx7ntYN9E19VndoD6B/c/HyYILoiBDMwI00cXjAB+NnEiZ5BklouOpYpZ7+3m9JfM9dlNdEBdOvag5xBw5bkCTrxB7NGwc+etnlfIhM="
