dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh | bash
notifications:
  slack:
    rooms:
      secure: "BD2bYTxTn1nWqBc8l4KMs/NdK4lTcnY2jwQGvThekOMMxgDXOR0T46Zfm03ZUgs6NTKpfyF3FKBX0Ofv++DPI62vmamzcu7zchb2W3YYmSLmRYNCWrqKUp1clghdPyX5U3rKdHlM4KIdjrjHiFmkO4Z5JwzG94uNLJY/3Z1yGNxE30ZVexWDiuLaoZJoyLkTrDTG32py8f2VKOOpubVmiQcieYUw4n+juR1oDlts88vbeqMKvInw+u/PRcDMozDdG8gha7SUQAu7DVcQZ0idqyaaBXilpOL0gKyNLOREg0aaUL6thFwipdq9kr0XhcZ7COxCmZlZXaa31vvuhfNDiZri73kstxgjIPUqw9LYEcYoxg4RWTNnvSGFsl2y3EKVnFMkSh473Q3e2AJhjvqf0iio9RGARP42hTUWpTVdWLdvjZvSBylt3jidLdlyME4s3g+kz+moRpU6qjnsHxtC2/PtQnXvABckdUjcpJVZrDXn4k5eI19Peb20Tqxy7yIllcnikD7VwWrQBGIDA0GsZNkrHqlM8+P8jCPSHgkOLv2n6yDUeO8s+9n2DK5tqSWlIjAWy27KqrcTF03sRS+YkhCvOFMN3inHNmQv44XAqSwqib2a4tErioYBHfhuVFC8Ar191bYk4gYnsLSHwcB7OZgmuCPHnhQKNQYMh2IZxbQ="
